name: Development Deploy
on:
  push:
    branches: [ development ]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW: ~/Documents/Deploys/
      DEPLOY_BRANCH: development
    steps:
    - name: Deploying into development environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: ${{ secrets.SERVER_USERNAME }}
        script: |
          cd ${{ env.GITHUB_WORKFLOW }}
          rm -rf Search-My-Pet
          git clone https://github.com/Search-My-Pet/search-my-pet-api.git
          cd search-my-pet-api
          npm install
          npx kill-port 15001
          npm run build
          nohup npm run start:prod >> ../dev-api.log