name: Testing environment
on:
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: Automated Test
    runs-on: ubuntu-latest
    env:
      TEST_BRANCH: ${{ github.head_ref || github.ref_name }} 
      TEST_REPOSITORY_URL: https://github.com/inclusive-pet/inclusive-pet-api.git
      TEST_REPOSITORY_NAME: inclusive-pet-api
      TEST_DIRECTORY: /home/muryllo/Documents/Tests
      TEST_COMMAND: npm test
    steps:
    - name: Setting up the test environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: ${{ secrets.SERVER_USERNAME }}
        script: |
          echo "Running script to test into server..."
          pwd

          UNSAFE_BRANCH_NAME=${{ env.TEST_BRANCH }}
          SAFE_BRANCH_NAME=${UNSAFE_BRANCH_NAME/\//-}

          BASE_PATH="${{ env.TEST_DIRECTORY }}/${SAFE_BRANCH_NAME}"
          FULL_PATH="${BASE_PATH}/${{ env.TEST_REPOSITORY_NAME }}"

          if [ -d "$FULL_PATH" ]; then
            cd $FULL_PATH
            git reset --hard
            git pull origin ${{ env.TEST_BRANCH }}
          else
            mkdir -p $BASE_PATH
            cd $BASE_PATH
            git clone -b ${{ env.TEST_BRANCH }} --single-branch ${{ env.TEST_REPOSITORY_URL }}
            cd ${{ env.TEST_REPOSITORY_NAME }}
          fi

          TEST_ENV_FILE="${{ env.TEST_DIRECTORY }}/.env"

          [ ! -f $TEST_ENV_FILE ] || cp $TEST_ENV_FILE $FULL_PATH

          npm install

          ${{ env.TEST_COMMAND }}

          cd ${{ env.TEST_DIRECTORY }}
          rm -rf $SAFE_BRANCH_NAME